### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DaDevGuy** [vecnavium-pm-pl/SkyBlocksPM#11]
So When i join server server closed and 
Call to undefined method Vecnavium\SkyBlocksPM\SkyBlocksPM::getDataBase()" (EXCEPTION) in "plugins/SkyBlocksPM.phar/src/Vecnavium/SkyBlocksPM/player/PlayerManager" at line 18
got this error

**Comment by DaDevGuy** [comment]
[13:36:22.090] [Server thread/CRITICAL]: Error: "Call to undefined method Vecnavium\SkyBlocksPM\SkyBlocksPM::getDataBase()" (EXCEPTION) in "plugins/SkyBlocksPM.phar/src/Vecnavium/SkyBlocksPM/player/PlayerManager" at line 18
--- Stack trace ---
  #0 plugins/SkyBlocksPM.phar/src/Vecnavium/SkyBlocksPM/listener/EventListener(34): Vecnavium\SkyBlocksPM\player\PlayerManager->loadPlayer(object pocketmine\player\Player#80965)
  #1 pmsrc/src/event/RegisteredListener(75): Vecnavium\SkyBlocksPM\listener\EventListener->onJoin(object pocketmine\event\player\PlayerJoinEvent#182438)
  #2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerJoinEvent#182438)
  #3 pmsrc/src/player/Player(817): pocketmine\event\Event->call()
  #4 pmsrc/src/network/mcpe/NetworkSession(711): pocketmine\player\Player->doFirstSpawn()
  #5 pmsrc/src/network/mcpe/NetworkSession(704): pocketmine\network\mcpe\NetworkSession->onClientSpawnResponse()
  #6 pmsrc/src/network/mcpe/handler/SpawnResponsePacketHandler(44): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #7 pmsrc/vendor/pocketmine/bedrock-protocol/src/SetLocalPlayerAsInitializedPacket(42): pocketmine\network\mcpe\handler\SpawnResponsePacketHandler->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#182451)
  #8 pmsrc/src/network/mcpe/NetworkSession(395): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\handler\SpawnResponsePacketHandler#174207)
  #9 pmsrc/src/network/mcpe/NetworkSession(358): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#182451, string[2] q.)
  #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[45] c*d4...p...F..a...."..N.....P..gd.....MX..D..)
  #11 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[54] ...~.fF.].e.N._7g.W...,q.G...}#F<.2&.A.\.....u.h..u...)
  #12 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#77906)
  #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #15 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1646224582.132)
  #16 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
  #17 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #18 pmsrc/src/PocketMine(327): pocketmine\server()
  #19 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by Vecnavium** [comment]
What plugin version is this you are using?

**Comment by Vecnavium** [comment]
Closing this issue. Recreate a new one and fill in all the information when creating the issue (Added issues template)
