### ISSUE TITLE
Server Crashed

### ISSUE THREAD

**Issue by DaDevGuy** [vecnavium-pm-pl/SkyBlocksPM#12]
[13:36:22.090] [Server thread/CRITICAL]: Error: "Call to undefined method Vecnavium\SkyBlocksPM\SkyBlocksPM::getDataBase()" (EXCEPTION) in "plugins/SkyBlocksPM.phar/src/Vecnavium/SkyBlocksPM/player/PlayerManager" at line 18
--- Stack trace ---
#0 plugins/SkyBlocksPM.phar/src/Vecnavium/SkyBlocksPM/listener/EventListener(34): Vecnavium\SkyBlocksPM\player\PlayerManager->loadPlayer(object pocketmine\player\Player#80965)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/pull/1 pmsrc/src/event/RegisteredListener(75): Vecnavium\SkyBlocksPM\listener\EventListener->onJoin(object pocketmine\event\player\PlayerJoinEvent#182438)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/2 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerJoinEvent#182438)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/3 pmsrc/src/player/Player(817): pocketmine\event\Event->call()
https://github.com/vecnavium-pm-pl/SkyBlocksPM/pull/4 pmsrc/src/network/mcpe/NetworkSession(711): pocketmine\player\Player->doFirstSpawn()
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/5 pmsrc/src/network/mcpe/NetworkSession(704): pocketmine\network\mcpe\NetworkSession->onClientSpawnResponse()
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/6 pmsrc/src/network/mcpe/handler/SpawnResponsePacketHandler(44): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe{closure}()
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/7 pmsrc/vendor/pocketmine/bedrock-protocol/src/SetLocalPlayerAsInitializedPacket(42): pocketmine\network\mcpe\handler\SpawnResponsePacketHandler->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#182451)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/8 pmsrc/src/network/mcpe/NetworkSession(395): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\handler\SpawnResponsePacketHandler#174207)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/9 pmsrc/src/network/mcpe/NetworkSession(358): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#182451, string[2] q.)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/pull/10 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[45] c*d4...p...F..a...."..N.....P..gd.....MX..D..)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/11 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[54] ...~.fF.].e.N._7g.W...,q.G...}#F<.2&.A......u.h..u...)
#12 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#77906)
#13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib{closure}()
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#15 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1646224582.132)
#16 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
#17 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#18 pmsrc/src/PocketMine(327): pocketmine\server()
#19 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by DaDevGuy** [comment]
So Getting This Issue

**Comment by Vecnavium** [comment]
Please respond to the issue template that is given to you when you create the issue, not saying to not provide the error but actually respond to the issue template given so I can actually help and know which version is causing this.

**Comment by Vecnavium** [comment]
I have noticed the issue, it has been fixed in the v1.0.3 release you can get the download [here](https://github.com/vecnavium-pm-pl/SkyBlocksPM/releases/tag/v1.0.3)
