### ISSUE TITLE
Server Crashed On Sb Tp

### ISSUE THREAD

**Issue by DaDevGuy** [vecnavium-pm-pl/SkyBlocksPM#15]
**Describe the bug**
So I Setted up Island And Created island now i was in lobby and i executed command /sb tp And Server Crashed With Error

# Error
#0 pmsrc/src/world/Position(53): pocketmine\world\Position->__construct(integer 253, integer 63, integer 273, object pocketmine\world\Worldhttps://github.com/vecnavium-pm-pl/SkyBlocksPM/pull/167919)
#1 pmsrc/src/world/Position(97): pocketmine\world\Position::fromObject(object pocketmine\math\Vector3https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/214829, object pocketmine\world\World#167919)
#2 pmsrc/vendor/pocketmine/math/src/Vector3(151): pocketmine\world\Position->getSide(integer 1, integer 1)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/3 plugins/SkyBlocksPM (1).phar/src/Vecnavium/SkyBlocksPM/commands/subcommands/TpSubCommand(32): pocketmine\math\Vector3->up()
https://github.com/vecnavium-pm-pl/SkyBlocksPM/pull/4 plugins/SkyBlocksPM (1).phar/src/Vecnavium/SkyBlocksPM/libs/CortexPE/Commando/BaseCommand(143): Vecnavium\SkyBlocksPM\commands\subcommands\TpSubCommand->onRun(object pocketmine\player\Player#81007, string[2] sb, array[0])
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/5 pmsrc/src/command/SimpleCommandMap(220): Vecnavium\SkyBlocksPM\libs\CortexPE\Commando\BaseCommand->execute(object pocketmine\player\Player#81007, string[2] sb, array[0])
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/6 pmsrc/src/Server(1408): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#81007, string[5] sb tp)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/7 pmsrc/src/player/Player(1382): pocketmine\Server->dispatchCommand(object pocketmine\player\Playerhttps://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/81007, string[5] sb tp)
#8 pmsrc/src/network/mcpe/handler/InGamePacketHandler(758): pocketmine\player\Player->chat(string[6] /sb tp)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/9 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(51): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#214960)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/pull/10 pmsrc/src/network/mcpe/NetworkSession(395): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#186154)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/11 pmsrc/src/network/mcpe/NetworkSession(358): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#214960, string[27] M./sb tp..E../.=..[$..]....)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/12 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[74] ..e./NR().....>.-..h......30.OL...(...9Mm.s..T.Y3..d..W.........8z......)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/pull/13 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[83] .u......b{r..O...c^...`....?e.7h..*......h...fNO.,TZ.0....I.+...ze....3.5d.|s9.)
https://github.com/vecnavium-pm-pl/SkyBlocksPM/issues/14 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#80209)
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib{closure}()
#16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#17 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1646233395.8733)
#18 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
#19 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
#20 pmsrc/src/PocketMine(327): pocketmine\server()
#21 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**To Reproduce**

**Expected behavior**
**SkyBlocksPM plugin information**

- Plugin Version: [e.g. 1.0.0]

**Screenshots**

**Additional context**

**Comment by Vecnavium** [comment]
**Please respond to the ISSUE **TEMPLATE..** I don't know if you are trolling but RESPOND to the templates so I get the full details on the issue. And as I said the issue is something you are doing while the plugin works just fine for me as I tested it on v1.0.3 which is the current latest release.

**Comment by DaDevGuy** [comment]
uhh Please idk github

**Comment by Vecnavium** [comment]
Either way, as I told you the issue is something on your side and NOT a plugin issue as I have tested it myself so as other users using it and are not running into any problems
