### ISSUE TITLE
Delete Island Bug

### ISSUE THREAD

**Issue by PushkarOP** [vecnavium-pm-pl/SkyBlocksPM#16]
**Describe the bug**
Delete Island Bug Crash The Server

**To Reproduce**
After doing /is delete {player name}

**Expected behavior**
I thought it would delete the island
**SkyBlocksPM plugin information**

- Plugin Version: 1.0.4

# Crash Dump
PocketMine-MP Crash Dump Fri Mar 11 10:35:43 UTC 2022

Error: Call to a member function getMembers() on null
File: plugins/SkyBlocksPM/src/Vecnavium/SkyBlocksPM/commands/subcommands/DeleteSubCommand
Line: 43
Type: Error

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: SkyBlocksPM

Code:
[34]             $sender->sendMessage(SkyBlocksPM::getInstance()->getMessages()->getMessage('not-registered'));
[35]             return;
[36]         }
[37]         if ($skyblockPlayer->getSkyBlock() == '')
[38]         {
[39]             $sender->sendMessage(SkyBlocksPM::getInstance()->getMessages()->getMessage('no-island'));
[40]             return;
[41]         }
[42]         $skyblock = SkyBlocksPM::getInstance()->getSkyBlockManager()->getSkyBlock($skyblockPlayer->getSkyBlock());
[43]         foreach ($skyblock->getMembers() as $member)
[44]         {
[45]             $player = SkyBlocksPM::getInstance()->getServer()->getPlayerByPrefix($member);
[46]             if ($player instanceof P)
[47]                 $player->teleport(SkyBlocksPM::getInstance()->getServer()->getWorldManager()->getDefaultWorld()->getSpawnLocation());
[48]             SkyBlocksPM::getInstance()->getPlayerManager()->getPlayerByPrefix($member)->setSkyBlock('');
[49]         }
[50]         SkyBlocksPM::getInstance()->getSkyBlockManager()->deleteSkyBlock($skyblock->getName());
[51]         $world = SkyBlocksPM::getInstance()->getServer()->getWorldManager()->getWorldByName($skyblock->getWorld());
[52]         foreach ($world->getPlayers() as $p)
[53]             $p->teleport(SkyBlocksPM::getInstance()->getServer()->getWorldManager()->getDefaultWorld()->getSpawnLocation());

Backtrace:
#0 plugins/SkyBlocksPM/src/Vecnavium/SkyBlocksPM/libs/CortexPE/Commando/BaseCommand(143): Vecnavium\SkyBlocksPM\commands\subcommands\DeleteSubCommand->onRun(object pocketmine\player\Player#101726, string[2] is, array[1])
#1 pmsrc/src/command/SimpleCommandMap(220): Vecnavium\SkyBlocksPM\libs\CortexPE\Commando\BaseCommand->execute(object pocketmine\player\Player#101726, string[2] is, array[1])
#2 pmsrc/src/Server(1408): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#101726, string[25] is delete PushkarMCPE5031)
#3 pmsrc/src/player/Player(1382): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#101726, string[25] is delete PushkarMCPE5031)
#4 pmsrc/src/network/mcpe/handler/InGamePacketHandler(164): pocketmine\player\Player->chat(string[27] ./is delete PushkarMCPE5031)
#5 pmsrc/vendor/pocketmine/bedrock-protocol/src/TextPacket(167): pocketmine\network\mcpe\handler\InGamePacketHandler->handleText(object pocketmine\network\mcpe\protocol\TextPacket#132906)
#6 pmsrc/src/network/mcpe/NetworkSession(397): pocketmine\network\mcpe\protocol\TextPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#117552)
#7 pmsrc/src/network/mcpe/NetworkSession(360): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\TextPacket#132906, string[65] ....PushkarMCPE5031../is delete PushkarMCPE5031.2535445334734711.)
#8 pmsrc/src/network/mcpe/raklib/RakLibInterface(192): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[98] s.dd..(-..N,.u.p5506....,VHI.I-IU@..02565115661."CC....9?Z.nU.9.Nlp...uJSkpf...x)
#9 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[107] .]../...E.6...W...1 ....I..:.....K2........{...=.b.J........[..nc.R.w.........+.)
#10 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#27952)
#11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#13 pmsrc/src/Server(1660): pocketmine\snooze\SleeperHandler->sleepUntil(double 1646994943.1691)
#14 pmsrc/src/Server(1046): pocketmine\Server->tickProcessor()
#15 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[72] /storage/emulated/0/Android/data/io.scer.pocketmine/files/PocketMine-MP/, string[80] /storage/emulated/0/Android/data/io.scer.pocketmine/files/PocketMine-MP/plugins/)
#16 pmsrc/src/PocketMine(327): pocketmine\server()
#17 pmsrc(11): require(string[116] phar:///storage/emulated/0/Android/data/io.scer.pocketmine/files/PocketMine-MP/P)

PocketMine-MP version: 4.2.2 [Protocol 486]
Git commit: 12946fbe466335ccf9d94f63a65400903c924fca
uname -a: Linux localhost 4.9.112-perf+ #1 SMP PREEMPT Wed Aug 19 02:45:37 CST 2020 aarch64
PHP Version: 8.0.12
Zend version: 4.0.12
OS: Linux, android
Composer libraries: 
- adhocore/json-comment 1.1.2@fc2f76979f0a44a5f5bc2a2b600d0762fe0e78e7
- brick/math 0.9.3@ca57d18f028f84f777b2168cd1911b0dee2343ae
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.4.0@eef488991d53e58e60c9554b09b1201ca5ba9296
- netresearch/jsonmapper v4.0.0@8bbc021a8edb2e4a7ea2f8ad4fa9ec9dce2fcb8d
- pocketmine/bedrock-data 1.6.0+bedrock-1.18.10@e98c511584a7bd58a95986374d2df4b04c6a2ba0
- pocketmine/bedrock-protocol 8.0.0+bedrock-1.18.10@017e57c8f8a74118bcbba7332e7ebac9e6c81693
- pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.2.0@49ea303993efdfb39cd302e2156d50aa78209e78
- pocketmine/color 0.2.0@09be6ea6d76f2e33d6813c39d29c22c46c17e1d2
- pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
- pocketmine/locale-data 2.4.3@4d0b081f1a79407e087968ea76aaf330db6ea2b5
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/log-pthreads 0.4.0@61f709e8cf36bcc24e4efe02acded680a1ce23cd
- pocketmine/math 0.4.2@aacc3759a508a69dfa5bc4dfa770ab733c5c94bf
- pocketmine/nbt 0.3.2@3e0d9ef6b6c5fb45e3745a121296e75631b3eefe
- pocketmine/pocketmine-mp 4.2.2@12946fbe466335ccf9d94f63a65400903c924fca
- pocketmine/raklib 0.14.3@4798576fec0364266dce23b368a7fec5e5de7927
- pocketmine/raklib-ipc 0.1.1@922a6444b0c6c7daaa5aa5a832107e1ec4738aed
- pocketmine/snooze 0.3.1@0ac8fc2a781c419a1f64ebca4d5835028f59e29b
- ramsey/collection 1.2.2@cccc74ee5e328031b15640b51056ee8d3bb66c0a
- ramsey/uuid 4.2.3@fc9bb7fb5388691fd7373cd44dcb4d63bbcf24df
- rhumsaa/uuid unknown@unknown
- symfony/polyfill-ctype v1.24.0@30885182c981ab175d4d034db0f6f469898070ab
- symfony/polyfill-php80 v1.24.0@57b712b08eddb97c762a8caa32c84e037892d2e9
- symfony/polyfill-php81 v1.24.0@5de4ba2d41b15f9bd0e19b2ab9674135813ec98f
- webmozart/assert 1.10.0@6964c76c7804814a842473e0c8fd15bab0f18e25
- webmozart/path-util 2.3.0@d939f7edc24c9a1bb9c0dee5cb05d8e859490725

Loaded plugins:
DEVirion 1.2.8 by poggit, SOFe for API(s) 4.0.0
DevTools 1.15.0 by PocketMine Team for API(s) 4.0.0
EconomyAPI 5.7.3-PM4 by onebone for API(s) 4.0.0
FakePlayer 0.1.2 by  for API(s) 4.0.0
FormAPI 2.1.0 by jojoe77777 for API(s) 4.0.0
MultiWorld 1.7.0-beta4 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 4.0.0
PurePerms 2.0.2 by Vecnavium , 64FF00 & ProjectInfinity for API(s) 4.0.0
SkyBlocksPM 1.0.4 by Vecnavium for API(s) 4.0.0

**Comment by Vecnavium** [comment]
Fixed in [this release](https://github.com/vecnavium-pm-pl/SkyBlocksPM/releases/tag/v1.0.7)
