### ISSUE TITLE
/is lock and /is unlock

### ISSUE THREAD

**Issue by PushkarOP** [vecnavium-pm-pl/SkyBlocksPM#18]
Add /is lock
And /is unlock
It will be good 🙂

**Comment by Vecnavium** [comment]
Fixed in  [this release](https://github.com/vecnavium-pm-pl/SkyBlocksPM/releases/tag/v1.0.7)

**Comment by PushkarOP** [comment]
.

**Comment by DaDevGuy** [comment]
yes add this please
