### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by incharon093** [vecnavium-pm-pl/SkyBlocksPM#19]
[Server thread/CRITICAL]: ErrorException: "Undefined array key "SnakierCoast100"" (EXCEPTION) in 
"plugins/SkyBlocksPM-stable/src/Vecnavium/SkyBlocksPM/player/PlayerManager" at line 54

**Comment by ErikPDev** [comment]
#27

**Comment by Vecnavium** [comment]
Please download SkyBlocksPM v1.0.8 from https://github.com/vecnavium-pm-pl/SkyBlocksPM/releases/tag/v1.0.8. This new version has been submitted and will be reviewed by a Poggit staff later.
