### ISSUE TITLE
Island Top

### ISSUE THREAD

**Issue by YT-Duckyyy** [vecnavium-pm-pl/SkyBlocksPM#2]
Add an island top command, leaderboard as well (entity/floating text)

/is top for example

This is based of island points? Which you can obtain by leveling up your island, killing players, crates and stuffs (crates etcetc wouldn't be ur side but capable of giving island points as an admin)

**Comment by Vecnavium** [comment]
I am likely going to do an API (Such as top 10 islands, leaderboards and etc) for SkyBlocksPM therefore people can create their own plugins to create such a system. Possibly [VecnaLeaderboards](https://github.com/vecnavium-pm-pl/VecnaLeaderboards) might support SkyBlocksPM for specific leaderboards but I do not think I will implement /sb top.

All this also falls into what I said about your Island Points suggestions. I might so a basic Island Points such as breaking ores but not extremely extensive like what you said. But most of what you said should be created by your own or another plugin and not into SkyBlocksPM
