### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DaDevGuy** [vecnavium-pm-pl/SkyBlocksPM#20]
# Features To Add

* `/is kick` Kicks A Player From Island.
* `/is lock` Locks Island For Public Visits.
* `/is unlock` Unlocks Island For Public Visits.

**Comment by cosmicnebula200** [comment]
island settings are already in the TODO of the plugin. I wont be doing much until vecna wakes up to reality and does it himself or asks me to do it :>

**Comment by DaDevGuy** [comment]
lol

**Comment by Vecnavium** [comment]
> island settings are already in the TODO of the plugin. I wont be doing much until vecna wakes up to reality and does it himself or asks me to do it :>

Wake up to reality cosmic, nothing goes as planned in this acursed world. - Madara Uchiha.

**Comment by DaDevGuy** [comment]
lol

**Comment by BhawaniTheKing** [comment]
> 

LoL You Are Right

**Comment by DaDevGuy** [comment]
the heck bs gaming here

`MeoW#0001` dm me

**Comment by GabBiswajit** [comment]
Bhawani Can You Reply In Discord I No Youz Scam My 20$

**Comment by GabBiswajit** [comment]
> 

Reply I'm dc i add all

**Comment by GabBiswajit** [comment]
> 

I think scamer gaming xD
