### ISSUE TITLE
Island Create Enhancement

### ISSUE THREAD

**Issue by DaDevGuy** [vecnavium-pm-pl/SkyBlocksPM#21]
Save Island World name As Player's Name

**Comment by cosmicnebula200** [comment]
Why tho

**Comment by DaDevGuy** [comment]
just for making my worlds folder looks a bit cleaner

**Comment by PushkarOP** [comment]
Lol

**Comment by DaDevGuy** [comment]
xD

**Comment by Vecnavium** [comment]
How does doing this make your worlds folder cleaner..

**Comment by DaDevGuy** [comment]
Players names look cleaner then uuid

**Comment by xRodzMC** [comment]
> Players names look cleaner then uuid

This uuid is used to identify the player. If your username is duplicates... It can be overwritten if we use player names that are same.
