### ISSUE TITLE
/IS invite

### ISSUE THREAD

**Issue by Zerilia** [vecnavium-pm-pl/SkyBlocksPM#22]
**Describe the bug**
When i write /IS invite thé plugin tell me "You dont have island"

**Comment by cosmicnebula200** [comment]
what does "You dont have an island" mean.

**Comment by Zerilia** [comment]
When i  /IS invite player i cant invit

**Comment by Zerilia** [comment]
Come to discord  Erreur 404#7908

**Comment by cosmicnebula200** [comment]
dude just use brains, create an island before inviting someone smh
