### ISSUE TITLE
Small BUG

### ISSUE THREAD

**Issue by DaDevGuy** [vecnavium-pm-pl/SkyBlocksPM#28]
`/is invite <player_name>` should send a invitation to player but it keep sending message You Don't have a skyblock island...
while i have a skyblock island

**Comment by cosmicnebula200** [comment]
are you sure you actually created the island and the player you are inviting does not own one

**Comment by DaDevGuy** [comment]
yes 100%

**Comment by Vecnavium** [comment]
Keep a download of the data of SkyBlocksPM, delete it then restart the server and try again (create island and invite a player) if it works then it's likely some wonky shit going on.

**Comment by DuoIncure** [comment]
This is fixed in #36

**Comment by Vecnavium** [comment]
Please download SkyBlocksPM v1.0.8 from https://github.com/vecnavium-pm-pl/SkyBlocksPM/releases/tag/v1.0.8. This new version has been submitted and will be reviewed by a Poggit staff later.
