### ISSUE TITLE
ErrorException: "ZipArchive::close(): Can't open file: Permission denied"

### ISSUE THREAD

**Issue by Ifera** [vecnavium-pm-pl/SkyBlocksPM#3]
Got this error when using the command `/sb setworld`.
I have attached the crashdump for further info. Running on Windows 11.
Crashdump: [Sat_Feb_19-23.29.55-PKT_2022.log](https://github.com/vecnavium-pm-pl/SkyBlocksPM/files/8102773/Sat_Feb_19-23.29.55-PKT_2022.log)

**Comment by Vecnavium** [comment]
The issue has been fixed with [this release](https://github.com/vecnavium-pm-pl/SkyBlocksPM/releases/tag/v1.0.1)
