### ISSUE TITLE
Major Bug

### ISSUE THREAD

**Issue by YT-Duckyyy** [vecnavium-pm-pl/SkyBlocksPM#31]
**Describe the bug**
A clear and concise description of what the bug is. I rejoined the server and it crashes.

**To Reproduce**
Not sure but all I did was:
Create an Islans
Restart server
Then join, server will crash

**Expected behavior**
**SkyBlocksPM plugin information**

- Plugin Version: [e.g. 1.0.0] Latest Approved Poggit 

**Screenshots**

**Additional context**
Error msg:
@no help...
[22:53:38.405] [Server thread/CRITICAL]: ErrorException: "Undefined array key "DuckyYT4979"" (EXCEPTION) in "plugins/SkyBlocksPM.phar/src/Vecnavium/SkyBlocksPM/player/PlayerManager" at line 54
--- Stack trace ---
  #0 plugins/SkyBlocksPM.phar/src/Vecnavium/SkyBlocksPM/player/PlayerManager(54): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[33] Undefined array key "DuckyYT4979", string[98] phar:///home/container/plugins/SkyBlocksPM.phar/src/Vecnavium/SkyBlocksPM/player, int 54)
  #1 plugins/SkyBlocksPM.phar/src/Vecnavium/SkyBlocksPM/player/PlayerManager(37): Vecnavium\SkyBlocksPM\player\PlayerManager->getPlayer(object ipad54\netherblocks\player\Player#127271)
  #2 plugins/SkyBlocksPM.phar/src/Vecnavium/SkyBlocksPM/listener/EventListener(43): Vecnavium\SkyBlocksPM\player\PlayerManager->unloadPlayer(object ipad54\netherblocks\player\Player#127271)
  #3 pmsrc/src/event/RegisteredListener(60): Vecnavium\SkyBlocksPM\listener\EventListener->onLeave(object pocketmine\event\player\PlayerQuitEvent#133935)
  #4 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerQuitEvent#133935)
  #5 pmsrc/src/player/Player(2100): pocketmine\event\Event->call()
  #6 pmsrc/src/network/mcpe/NetworkSession(578): pocketmine\player\Player->onPostDisconnect(string[17] client disconnect, null)
  #7 pmsrc/src/network/mcpe/NetworkSession(511): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #8 pmsrc/src/network/mcpe/NetworkSession(580): pocketmine\network\mcpe\NetworkSession->tryDisconnect(object Closure#133930, string[17] client disconnect)
  #9 pmsrc/src/network/mcpe/raklib/RakLibInterface(141): pocketmine\network\mcpe\NetworkSession->onClientDisconnect(string[17] client disconnect)
  #10 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(75): pocketmine\network\mcpe\raklib\RakLibInterface->onClientDisconnect(int 0, string[17] client disconnect)
  #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#102377)
  #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #14 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1660431218.4161)
  #15 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #16 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #17 pmsrc/src/PocketMine(327): pocketmine\server()
  #18 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by Vecnavium** [comment]
Please download SkyBlocksPM v1.0.8 from https://github.com/vecnavium-pm-pl/SkyBlocksPM/releases/tag/v1.0.8. This new version has been submitted and will be reviewed by a Poggit staff later.
