### ISSUE TITLE
create island

### ISSUE THREAD

**Issue by UnknownNull** [vecnavium-pm-pl/SkyBlocksPM#32]
**Describe the bug**
A player whose name ends with _.  For example: Example_ and trying to create Iceland will cause the server to crash

**To Reproduce**

**Expected behavior**
**SkyBlocksPM plugin information**

- Plugin Version: [1.0.7]

2022-08-14 [18:56:30.050] [Server thread/INFO]: [Track] <AMIRMORA_> /is create AMIRMORA_
2022-08-14 [18:56:30.050] [Server thread/CRITICAL]: ErrorException: "Undefined array key "AMIRMORA_"" (EXCEPTION) in "plugins/SkyBlocksPM-b65e52c90e7e579da44eda3b803639f10b52c317/src/Vecnavium/SkyBlocksPM/player/PlayerManager" at line 54
--- Stack trace ---
  #0 plugins/SkyBlocksPM-b65e52c90e7e579da44eda3b803639f10b52c317/src/Vecnavium/SkyBlocksPM/player/PlayerManager(54): pocketmine\errorhandler\ErrorToExceptionHandler::handle(int 2, string[31] Undefined array key "AMIRMORA_", string[155] C:\Users\Administrator\Documents\4.SkyBlock\plugins\SkyBlocksPM-b65e52c90e7e579d, int 54)
  #1 plugins/SkyBlocksPM-b65e52c90e7e579da44eda3b803639f10b52c317/src/Vecnavium/SkyBlocksPM/commands/subcommands/CreateSubCommand(30): Vecnavium\SkyBlocksPM\player\PlayerManager->getPlayer(object pocketmine\player\Player#32014)
  #2 plugins/SkyBlocksPM-b65e52c90e7e579da44eda3b803639f10b52c317/src/Vecnavium/SkyBlocksPM/libs/CortexPE/Commando/BaseCommand(143): Vecnavium\SkyBlocksPM\commands\subcommands\CreateSubCommand->onRun(object pocketmine\player\Player#32014, string[2] is, array[1])
  #3 pmsrc/src/command/SimpleCommandMap(205): Vecnavium\SkyBlocksPM\libs\CortexPE\Commando\BaseCommand->execute(object pocketmine\player\Player#32014, string[2] is, array[1])
  #4 pmsrc/src/Server(1446): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#32014, string[19] is create AMIRMORA_)
  #5 plugins/Slapper.phar/src/slapper/Main(238): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#32014, string[19] is create AMIRMORA_)
  #6 pmsrc/src/command/PluginCommand(50): slapper\Main->onCommand(object slapper\SlapperCommandSender#29098, object pocketmine\command\PluginCommand#25939, string[3] rca, array[3])
  #7 pmsrc/src/command/SimpleCommandMap(205): pocketmine\command\PluginCommand->execute(object slapper\SlapperCommandSender#29098, string[3] rca, array[4])
  #8 pmsrc/src/Server(1446): pocketmine\command\SimpleCommandMap->dispatch(object slapper\SlapperCommandSender#29098, string[37] rca "AMIRMORA_" is create "AMIRMORA_")
  #9 plugins/Slapper.phar/src/slapper/Main(706): pocketmine\Server->dispatchCommand(object slapper\SlapperCommandSender#29098, string[37] rca "AMIRMORA_" is create "AMIRMORA_")
  #10 pmsrc/src/event/RegisteredListener(60): slapper\Main->onEntityDamage(object pocketmine\event\entity\EntityDamageByEntityEvent#103026)
  #11 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\entity\EntityDamageByEntityEvent#103026)
  #12 pmsrc/src/entity/Entity(525): pocketmine\event\Event->call()
  #13 pmsrc/src/entity/Living(517): pocketmine\entity\Entity->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#103026)
  #14 pmsrc/src/player/Player(1741): pocketmine\entity\Living->attack(object pocketmine\event\entity\EntityDamageByEntityEvent#103026)
  #15 pmsrc/src/network/mcpe/handler/InGamePacketHandler(511): pocketmine\player\Player->attackEntity(object slapper\entities\SlapperHuman#31948)
  #16 pmsrc/src/network/mcpe/handler/InGamePacketHandler(301): pocketmine\network\mcpe\handler\InGamePacketHandler->handleUseItemOnEntityTransaction(object pocketmine\network\mcpe\protocol\types\inventory\UseItemOnEntityTransactionData#103054)
  #17 pmsrc/vendor/pocketmine/bedrock-protocol/src/InventoryTransactionPacket(105): pocketmine\network\mcpe\handler\InGamePacketHandler->handleInventoryTransaction(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#103047)
  #18 pmsrc/src/network/mcpe/NetworkSession(388): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#106299)
  #19 pmsrc/src/network/mcpe/NetworkSession(351): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\InventoryTransactionPacket#103047, string[32] ........6..Ar=.B.#!.............)
  #20 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[126] c.abb.b.jm..3.g.t;9.+.b....KM.JL+.*.I.L-b`P.c`f`d.a0[.......]Y....0...`.......iC)
  #21 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[135] .APB.4.....f2.F.+.;.8..~rp>|~....96... %Z..J...../e...D..E..?.Q^Bh..0..@......*.)
  #22 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#30195)
  #23 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #24 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
  #25 pmsrc/src/Server(1703): pocketmine\snooze\SleeperHandler->sleepUntil(float 1660487190.0427)
  #26 pmsrc/src/Server(1063): pocketmine\Server->tickProcessor()
  #27 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#4, string[44] C:\Users\Administrator\Documents\4.SkyBlock\, string[52] C:\Users\Administrator\Documents\4.SkyBlock\plugins\)
  #28 pmsrc/src/PocketMine(327): pocketmine\server()
  #29 pmsrc(11): require(string[83] phar://C:/Users/Administrator/Documents/4.SkyBlock/skyblock.phar/src/PocketMine.)
--- End of exception information ---
2022-08-14 [18:56:30.050] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2022-08-14 [18:56:30.097] [Server thread/EMERGENCY]: Please upload the "C:/Users/Administrator/Documents/4.SkyBlock/crashdumps/Sun_Aug_14-18.56.30-+0430_2022.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
2022-08-14 [18:56:30.097] [Server thread/EMERGENCY]: Forcing server shutdown

**Comment by Vecnavium** [comment]
Please download SkyBlocksPM v1.0.8 from https://github.com/vecnavium-pm-pl/SkyBlocksPM/releases/tag/v1.0.8. This new version has been submitted and will be reviewed by a Poggit staff later.
