### ISSUE TITLE
It was crash

### ISSUE THREAD

**Issue by Wengareki** [vecnavium-pm-pl/SkyBlocksPM#34]
![Screenshot_20221020-150819_Chrome](https://user-images.githubusercontent.com/116268141/196915795-1dac864a-7db8-4089-b220-ad2de9161465.jpg)
(https://github.com/vecnavium-pm-pl/SkyBlocksPM/files/9828541/Thu_Oct_20-09.26.35-UTC_2022.log)
**Describe the bug**

**To Reproduce**

**Expected behavior**
**SkyBlocksPM plugin information**

- Plugin Version: [e.g. 1.0.7]

**Screenshots**

**Additional context**

**Comment by Vecnavium** [comment]
Please download SkyBlocksPM v1.0.8 from https://github.com/vecnavium-pm-pl/SkyBlocksPM/releases/tag/v1.0.8. This new version has been submitted and will be reviewed by a Poggit staff later.
