### ISSUE TITLE
Please fix this

### ISSUE THREAD

**Issue by Wengareki** [vecnavium-pm-pl/SkyBlocksPM#37]
**Describe the bug**
FIX IT FAST.

**To Reproduce**

**SkyBlocksPM plugin information**

- Plugin Version: [e.g. 1.0.8]
![Screenshot_20221031-182941_Chrome](https://user-images.githubusercontent.com/116268141/199013810-d9a2cdb4-0bcb-4689-9dec-2f36ae9b2fd7.jpg)
.

**Comment by cosmicnebula200** [comment]
Thanks for opening a very "informative" issue, we will working on a fix as soon as we understand this huge "information" which you provided

**Comment by DuoIncure** [comment]
There is not enough information provided in this issue. We cannot fix a problem if we do not know the cause. If you would like to post the correct information required we will happily get back to you on it within 3-5 business months.
