### ISSUE TITLE
Crash xD

### ISSUE THREAD

**Issue by GabBiswajit** [vecnavium-pm-pl/SkyBlocksPM#42]
Error: Position world is null or has been unloaded
File: pmsrc/src/world/Position
Line: 70
Type: pocketmine\utils\AssumptionFailedError
Backtrace:
#0 pmsrc/src/entity/Entity(1428): pocketmine\world\Position->getWorld()
#1 pmsrc/src/player/Player(2420): pocketmine\entity\Entity->teleport(object pocketmine\world\Position#425620, null, null)
#2 plugins/SkyBlocksPM-1.0.9/src/Vecnavium/SkyBlocksPM/commands/subcommands/TpSubCommand(31):

**Comment by xRodzMC** [comment]
Please check your world if its loaded... You need to load the world before teleporting to a location/position.
