### ISSUE TITLE
Add sb home or I sue u

### ISSUE THREAD

**Issue by crischutu07** [vecnavium-pm-pl/SkyBlocksPM#5]

**Comment by Vecnavium** [comment]
What is /sb home exactly, what does it do should it do?

**Comment by PushkarOP** [comment]
It teleport to home position in island when player or visitor join island

**Comment by crischutu07** [comment]
> What is /sb home exactly, what does it do should it do?

Go to your island

**Comment by Vecnavium** [comment]
It is already a thing. /sb tp

**Comment by crischutu07** [comment]
> It is already a thing. /sb tp

Bro, is teleporting to my lobby

**Comment by cosmicnebula200** [comment]
> > It is already a thing. /sb tp
> 
> Bro, is teleporting to my lobby

have you tried using `/sb setworld` on the **correct** world. Using it on an unwanted world will make it generate the unwanted world as a skyblock island

**Comment by cosmicnebula200** [comment]
> It teleport to home position in island when player or visitor join island

Hello @PushkarOP ,

I will take a look at whats wrong and push changes soon 👍

**Comment by cosmicnebula200** [comment]
oh! just realized it was not a 🐛 but a description of the command 🤦‍♂️

**Comment by reyyan987** [comment]
Lol

**Comment by cosmicnebula200** [comment]
Shush lets not talk about it anymore
