### ISSUE TITLE
Island Delete

### ISSUE THREAD

**Issue by DaDevGuy** [vecnavium-pm-pl/SkyBlocksPM#7]
So When I Delete My Island It Give Me Server Closed

**Comment by Vecnavium** [comment]
I have a feeling you tried creating an island before /sb setworld and now you are trying to delete the island you created. If so then the solution is to delete SkyBlocksPM's plugin_data or specifically delete the .sqlite file and restart the server then you should be fine.
I am going to be adding checks later on for if the user hasn't /sb setworld they cannot /sb create so we can avoid this sort of issue

**Comment by DaDevGuy** [comment]
k
