### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by PushkarOP** [vecnavium-pm-pl/SkyBlocksPM#9]
More Features:
+ Scoreboard
+ Scoreboard Objective
+ Island Bank
+ Island Border
+ Island Level
+ Island Leaderboard
    - Most Blocks Mined Leaderboard
    - Most Placed Placed Leaderboard
    - Island Bank Leaderboard
+ Easy And Good API

**Comment by Vecnavium** [comment]
Most placed & broken blocks will not happen. That will just degrade the plugin's performance for an uneeded feature for the wrong plugin.
Scoreboard & Scoreboard objective, what do you mean by this exactly? And keep in mind it has to fit the scoreboard as well.
Easy and good API, I am considering on not doing it anymore.

**Comment by PushkarOP** [comment]
![download](https://user-images.githubusercontent.com/84075300/156002323-dfd1e8e4-4441-4c97-99f7-76ee30c36275.jpeg)
Scoreboard Like This

**Comment by PushkarOP** [comment]
And Skyblock API will be more good btw

**Comment by Vecnavium** [comment]
> ![download](https://user-images.githubusercontent.com/84075300/156002323-dfd1e8e4-4441-4c97-99f7-76ee30c36275.jpeg) Scoreboard Like This

I will think about it and see how it can be done and if it's possible on my side. (Doesn;t mean it will happen)

> And Skyblock API will be more good btw

Tell me what a SkyBlocks API can be used for and what you could possibly do with it and maybe I will reconsider it. Because no offence I have a slight feeling you don't know what a SkyBlocks API is used for

**Comment by PushkarOP** [comment]
I mean skyblock api to get island top, island bank, player island name, getting memebers of island ,like this

**Comment by Vecnavium** [comment]
Alright, but the API isn't going to all of that for you. You have to do the work for  getting the top island and the like but the API will provide the possibility for you to be able to get all skyblock members, island names list of skyblocks islands and etc which will do what you want to do if you make the plugin for it. 
I will think about it

**Comment by PushkarOP** [comment]
ok
